### ISSUE TITLE
issue about NetCDF

### ISSUE THREAD

**Issue by Geess126** [MiCurry/MPAS-Limited-Area#42]
Creating a regional mesh of  gansu.static.nc
Marking boundary  1 ...
Filling region ...
Creating boundary layer: 1  ... 2  ... 3  ... 4  ... 5  ... 6  ... 7  ... 8  ... DONE!
Marking region edges ...
Marking region vertices...
Subsetting mesh fields into the specified region mesh...
Traceback (most recent call last):
  File "./create_region", line 59, in <module>
    regional_area.gen_region(**kwargs)
  File "/my/kit/MPAS-Limited-Area/limited_area/limited_area.py", line 151, in gen_region
    **kwargs)
  File "/my/kit/MPAS-Limited-Area/limited_area/mesh.py", line 264, in subset_fields
    len(glbBdyEdgeIDs))
  File "netCDF4/_netCDF4.pyx", line 2562, in netCDF4._netCDF4.Dataset.createDimension
  File "netCDF4/_netCDF4.pyx", line 3370, in netCDF4._netCDF4.Dimension.__init__
  File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: NC_UNLIMITED size already in use

**Comment by Geess126** [comment]
@MiCurry Thanks.

**Comment by MiCurry** [comment]
Hi @Geess126, it would be great if you could provide more information on the region you are trying to create. Can you provide the contents of the `.pts` file that you are using? As well as the grid you are trying to produce. Providing the output of `ncdump -h grid.nc` on the grid you are trying to subset would be the most helpful.

As well, if could run `create_region` with `-v 5` and copy the output that would also greatly help.

**Comment by Geess126** [comment]
> Hi @Geess126, it would be great if you could provide more information on the region you are trying to create. Can you provide the contents of the `.pts` file that you are using? As well as the grid you are trying to produce. Providing the output of `ncdump -h grid.nc` on the grid you are trying to subset would be the most helpful.

Thanks, MiCurry! I found my static.nc file was not correct. It worked when I try the x1.163842.static.nc file in MPAS-tutorial, . Also if resolution of static.nc is small, and limit-area is also very small, it will show error, too.
